#!/bin/bash

echo "Run k6"


echo "=== Test parameters ==="
echo "NUMBER_ORG = $NUMBER_ORG
NUMBER_WORKSPACE = $NUMBER_WORKSPACE
NUMBER_DASHBOARD = $NUMBER_DASHBOARD
ENABLE_TABULAR_EXPORT = $ENABLE_TABULAR_EXPORT
DASHBOARD_NAME = $DASHBOARD_NAME
DATA_SOURCE_TYPE = $DATA_SOURCE_TYPE
WORKSPACE_ID = $WORKSPACE_ID
TEST_BRANCH = $TEST_BRANCH
SKIP_CACHE = $SKIP_CACHE
TAG_TEST = $TAG_TEST
SCENARIO_SCRIPT_NAME = $SCENARIO_SCRIPT_NAME
K6_INFLUXDB_BUCKET = $K6_INFLUXDB_BUCKET
K6_EXTRA_PARAMS = $K6_EXTRA_PARAMS
TIGER_VERSION = $TIGER_VERSION
MAX_VUS = $MAX_VUS
UPLOAD_TO_BI = $UPLOAD_TO_BI
SUBSCENARIO = $SUBSCENARIO
LIST_ORGS = LIST_ORGS
" ################################### TO BE UPDATED
