# (C) 2023 Tien Bien

name: Workflow dispatch example

on:
  workflow_dispatch:
    inputs:
      BUILD_ALL:
        description: 'BUILD_ALL'
        required: true
        type: boolean
      DATA_SOURCE_TYPE:
        description: 'DATA_SOURCE_TYPE'
        required: true
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
jobs:
  deploy:
    if: github.event.inputs.DATA_SOURCE_TYPE == 'snowflake'
    runs-on: ubuntu-latest
    steps:
      - name: Test
        if: ${{ github.event.inputs.DATA_SOURCE_TYPE }} == 'snowflake'
        run: echo "Test ${{ github.event.inputs.DATA_SOURCE_TYPE }} datasource."
