# (C) 2023 Tien Bien

name: Workflow dispatch example

on:
  workflow_dispatch:
    inputs:
      BUILD_ALL:
        description: 'BUILD_ALL'
        required: false
        type: boolean
        default: true
      EXTRA_PARAMETERS:
        description: 'EXTRA_PARAMETERS:'
        required: false
        type: string
        default: 'DATA_SOURCE_TYPE="redshift" DASHBOARD_NAME="Company insight" NUMBER_ORG=1 EXPORTED_FILE_FORMAT="CSV,XLSX" ENABLE_TABULAR_EXPORT=true LIST_ATTRIBUTE_FILTER="out_tpch_tab__lineitem.l_pk"'
  pull_request:
    branches: [ "demo" ]
  push:
    branches: [ "demo" ]
jobs:
  deploy:
    if: inputs.BUILD_ALL == true && github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo ${{ inputs.EXTRA_PARAMETERS }}
