# (C) 2023 Tien Bien

name: Workflow dispatch example

on:
  workflow_dispatch:
    inputs:
      BUILD_ALL:
        description: 'BUILD_ALL'
        required: false
        type: string
        default: 'false'

  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
jobs:
  deploy:
    if: ${{ inputs.BUILD_ALL }} == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo "Test ${{ github.event.inputs.BUILD_ALL }}."
