# (C) 2023 Tien Bien

name: Workflow dispatch example

on:
  workflow_dispatch:
    inputs:
      BUILD_ALL:
        description: 'BUILD_ALL'
        required: false
        type: boolean
        default: true
      LIST_PARAMETERS:
        description: 'LIST_PARAMETERS:'
        required: false
        type: string
        default: '{"DATA_SOURCE_TYPE":"redshift","DASHBOARD_NAME":"Company insight","NUMBER_ORG":"1","EXPORTED_FILE_FORMAT":"CSV,XLSX""ENABLE_TABULAR_EXPORT":true,"LIST_ATTRIBUTE_FILTER":"out_tpch_tab__lineitem.l_pk"}'
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
jobs:
  read-params:
    runs-on: ubuntu-latest
    outputs:
      params: $ {{ steps.set-params.ouputs.params }}
    steps:
      - id: set-params
        run: |
          echo "params= ${{ inputs.LIST_PARAMETERS }}" >> ./env_variables.json
  deploy:
    needs: [read-params]
    if: ${{ inputs.BUILD_ALL == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo "Test ${{ inputs.BUILD_ALL }}."
          cat ./env_variables.json
