# (C) 2023 Tien Bien

name: Workflow dispatch example

on:
  workflow_dispatch:
    inputs:
      BUILD_ALL:
        description: 'BUILD_ALL'
        required: true
        type: boolean
        default: true
      DATA_SOURCE_TYPE:
        description: 'DATA_SOURCE_TYPE'
        required: true
        default: 'redshift'
      DATA_SOURCE_TYPE_2:
        description: 'DATA_SOURCE_TYPE'
        required: true
        default: 'abcd'

  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
jobs:
  deploy:
    if: ${{ github.event.inputs.DATA_SOURCE_TYPE }} == 'snowflake'
    runs-on: ubuntu-latest
    steps:
      - name: Test
        if: ${{ github.event.inputs.DATA_SOURCE_TYPE }} == 'snowflake'
        run: |
          echo "Test ${{ github.event.inputs.BUILD_ALL }}."
          echo "Test ${{ github.event.inputs.DATA_SOURCE_TYPE }} datasource."
          echo "Test ${{ github.event.inputs.DATA_SOURCE_TYPE_2 }} datasource."
